services:

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./h_config:/config
    ports:
      - "8800:80"
      - "8843:443"
    restart: unless-stopped
